// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrq-FZsjffsVR3SlIFTTbocfWd6WxfoE',
    appId: '1:335461718945:web:484910098bc9019016c9e0',
    messagingSenderId: '335461718945',
    projectId: 'macjam1',
    authDomain: 'macjam1.firebaseapp.com',
    storageBucket: 'macjam1.appspot.com',
    measurementId: 'G-GRG7HZK469',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60ocsvgP8J_iLlY858QddTLhNSOkq518',
    appId: '1:335461718945:android:1217e6fe8f39b51d16c9e0',
    messagingSenderId: '335461718945',
    projectId: 'macjam1',
    storageBucket: 'macjam1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1G2KTMkrJayosaayb8EDiB4XLcJCzXTY',
    appId: '1:335461718945:ios:27b23910d98fd31216c9e0',
    messagingSenderId: '335461718945',
    projectId: 'macjam1',
    storageBucket: 'macjam1.appspot.com',
    iosClientId: '335461718945-uukhprem4lfjfetmq52vrereek6vnk1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.macjam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1G2KTMkrJayosaayb8EDiB4XLcJCzXTY',
    appId: '1:335461718945:ios:190704986ab8e47e16c9e0',
    messagingSenderId: '335461718945',
    projectId: 'macjam1',
    storageBucket: 'macjam1.appspot.com',
    iosClientId: '335461718945-avt2fuvqc88knsviteh3l1ji4ns1eees.apps.googleusercontent.com',
    iosBundleId: 'com.example.macjam2.RunnerTests',
  );
}
